

server:
  port: 8181
  
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_db
    username: root
    password: admin    
  jpa:
    show-sql: true
  
 
my:
#  feature-enabled: true
  
   
  